"""phase2c_demand_intelligence

Revision ID: 02d6674f9534
Revises: d961fb42716a
Create Date: 2026-08-27 01:09:24.918490

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d6674f9534'
down_revision: Union[str, None] = 'd961fb42716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('industry_demand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('industry_sector_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_demand_score', sa.Float(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_sector_id'], ['industry_sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_industry_demand_district_id', 'industry_demand', ['district_id'], unique=False)
    op.create_index('ix_industry_demand_job_role_id', 'industry_demand', ['job_role_id'], unique=False)
    op.create_index('ix_industry_demand_sector_id', 'industry_demand', ['industry_sector_id'], unique=False)
    op.create_index('ix_industry_demand_skill_id', 'industry_demand', ['skill_id'], unique=False)
    op.create_table('employer_survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['employer_surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=True),
    sa.Column('survey_response_id', sa.UUID(), nullable=True),
    sa.Column('raw_weight', sa.Float(), nullable=False),
    sa.Column('scaled_weight', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(job_posting_id IS NOT NULL AND survey_response_id IS NULL) OR (job_posting_id IS NULL AND survey_response_id IS NOT NULL)', name='ck_demand_signals_exclusive_source'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_response_id'], ['employer_survey_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_demand_signals_district_id', 'demand_signals', ['district_id'], unique=False)
    op.create_index('ix_demand_signals_job_role_id', 'demand_signals', ['job_role_id'], unique=False)
    op.create_index('ix_demand_signals_skill_id', 'demand_signals', ['skill_id'], unique=False)
    op.add_column('job_postings', sa.Column('data_source_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'job_postings', 'data_sources', ['data_source_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'data_source_id')
    op.drop_index('ix_demand_signals_skill_id', table_name='demand_signals')
    op.drop_index('ix_demand_signals_job_role_id', table_name='demand_signals')
    op.drop_index('ix_demand_signals_district_id', table_name='demand_signals')
    op.drop_table('demand_signals')
    op.drop_table('employer_survey_responses')
    op.drop_index('ix_industry_demand_skill_id', table_name='industry_demand')
    op.drop_index('ix_industry_demand_sector_id', table_name='industry_demand')
    op.drop_index('ix_industry_demand_job_role_id', table_name='industry_demand')
    op.drop_index('ix_industry_demand_district_id', table_name='industry_demand')
    op.drop_table('industry_demand')
    op.drop_table('industry_sectors')
    op.drop_table('employer_surveys')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
