"""phase4 training supply and planning

Revision ID: 09c9b7802578
Revises: e78b6ce1483f
Create Date: 2026-08-27 11:24:00.825338

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c9b7802578'
down_revision: Union[str, None] = 'e78b6ce1483f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_training_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'archived')", name='ck_district_plan_status'),
    sa.CheckConstraint('period_start <= period_end', name='ck_district_plan_period'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'period_start', 'period_end', name='uq_district_training_plan_period')
    )
    op.create_index('ix_district_training_plans_district_id', 'district_training_plans', ['district_id'], unique=False)
    op.create_table('training_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended')", name='ck_training_providers_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_assessed_date', sa.Date(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'pending', 'verified')", name='ck_candidate_skills_verification'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_id', name='uq_candidate_skill')
    )
    op.create_index('ix_candidate_skills_candidate_id', 'candidate_skills', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_skills_skill_id', 'candidate_skills', ['skill_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('sanctioned_seats', sa.Integer(), nullable=False),
    sa.Column('active_seats', sa.Integer(), nullable=False),
    sa.Column('utilized_seats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_course_offering_status'),
    sa.CheckConstraint('active_seats <= sanctioned_seats', name='ck_course_offering_active_limit'),
    sa.CheckConstraint('sanctioned_seats >= 0 AND active_seats >= 0 AND utilized_seats >= 0', name='ck_course_offering_nonnegative'),
    sa.CheckConstraint('utilized_seats <= active_seats', name='ck_course_offering_utilized_limit'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'course_id', 'district_id', name='uq_course_offering_scope')
    )
    op.create_index('ix_course_offerings_district_id', 'course_offerings', ['district_id'], unique=False)
    op.create_table('curricula',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'title', name='uq_curriculum_course_title')
    )
    op.create_table('district_training_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('demand_value', sa.Float(), nullable=True),
    sa.Column('supply_value', sa.Float(), nullable=True),
    sa.Column('gap_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['district_training_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_district_plan_items_plan_id', 'district_training_plan_items', ['plan_id'], unique=False)
    op.create_index('ix_district_plan_items_skill_id', 'district_training_plan_items', ['skill_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance')", name='ck_equipment_status'),
    sa.CheckConstraint('quantity >= 0 AND available_quantity >= 0 AND available_quantity <= quantity', name='ck_equipment_quantities'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_district_id', 'equipment', ['district_id'], unique=False)
    op.create_index('ix_equipment_provider_id', 'equipment', ['provider_id'], unique=False)
    op.create_table('trainers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_trainers_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['training_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trainers_provider_id', 'trainers', ['provider_id'], unique=False)
    op.create_table('course_equipment_requirements',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('required_quantity > 0', name='ck_course_equipment_required_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'equipment_id')
    )
    op.create_table('curriculum_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'retired')", name='ck_curriculum_version_status'),
    sa.CheckConstraint('version_number > 0', name='ck_curriculum_version_positive'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'version_number', name='uq_curriculum_version')
    )
    op.create_table('trainer_skills',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("verification_status IN ('unverified', 'pending', 'verified')", name='ck_trainer_skills_verification'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_id', 'skill_id')
    )
    op.create_table('curriculum_skills',
    sa.Column('curriculum_version_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.CheckConstraint("importance IN ('mandatory', 'preferred', 'nice_to_have')", name='ck_curriculum_skills_importance'),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curriculum_version_id', 'skill_id')
    )
    op.create_index('ix_curriculum_skills_skill_id', 'curriculum_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_curriculum_skills_skill_id', table_name='curriculum_skills')
    op.drop_table('curriculum_skills')
    op.drop_table('trainer_skills')
    op.drop_table('curriculum_versions')
    op.drop_table('course_equipment_requirements')
    op.drop_index('ix_trainers_provider_id', table_name='trainers')
    op.drop_table('trainers')
    op.drop_index('ix_equipment_provider_id', table_name='equipment')
    op.drop_index('ix_equipment_district_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_district_plan_items_skill_id', table_name='district_training_plan_items')
    op.drop_index('ix_district_plan_items_plan_id', table_name='district_training_plan_items')
    op.drop_table('district_training_plan_items')
    op.drop_table('curricula')
    op.drop_index('ix_course_offerings_district_id', table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index('ix_candidate_skills_skill_id', table_name='candidate_skills')
    op.drop_index('ix_candidate_skills_candidate_id', table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_table('training_providers')
    op.drop_index('ix_district_training_plans_district_id', table_name='district_training_plans')
    op.drop_table('district_training_plans')
    # ### end Alembic commands ###
