"""phase7b1 extend course master metadata

Revision ID: 1894783f5fe2
Revises: ce2f98973f2a
Create Date: 2026-08-27 13:40:41.202238

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1894783f5fe2'
down_revision: Union[str, None] = 'ce2f98973f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('source_course_code', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('qualification', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('cost_category', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('courses', sa.Column('nsqf_level', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('nqr_code', sa.String(length=150), nullable=True))
    op.add_column('courses', sa.Column('source_version', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('industry_sector_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('data_source_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('ingestion_run_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('source_record_identifier', sa.String(length=255), nullable=True))
    op.add_column('courses', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_courses_data_source_id', 'courses', ['data_source_id'], unique=False)
    op.create_index('ix_courses_ingestion_run_id', 'courses', ['ingestion_run_id'], unique=False)
    op.create_index('ix_courses_source_course_code', 'courses', ['source_course_code'], unique=False)
    op.create_unique_constraint('uq_courses_source_course_code', 'courses', ['data_source_id', 'source_course_code'])
    op.create_unique_constraint('uq_courses_source_nqr_version', 'courses', ['data_source_id', 'nqr_code', 'source_version'])
    op.create_foreign_key(None, 'courses', 'industry_sectors', ['industry_sector_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'courses', 'data_ingestion_runs', ['ingestion_run_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'courses', 'data_sources', ['data_source_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint('ck_courses_nsqf_level_nonnegative', 'courses', 'nsqf_level IS NULL OR nsqf_level >= 0')
    op.create_check_constraint('ck_courses_rate_nonnegative', 'courses', 'rate_per_hour IS NULL OR rate_per_hour >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_courses_rate_nonnegative', 'courses', type_='check')
    op.drop_constraint('ck_courses_nsqf_level_nonnegative', 'courses', type_='check')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint('uq_courses_source_nqr_version', 'courses', type_='unique')
    op.drop_constraint('uq_courses_source_course_code', 'courses', type_='unique')
    op.drop_index('ix_courses_source_course_code', table_name='courses')
    op.drop_index('ix_courses_ingestion_run_id', table_name='courses')
    op.drop_index('ix_courses_data_source_id', table_name='courses')
    op.drop_column('courses', 'source_updated_at')
    op.drop_column('courses', 'source_record_identifier')
    op.drop_column('courses', 'ingestion_run_id')
    op.drop_column('courses', 'data_source_id')
    op.drop_column('courses', 'industry_sector_id')
    op.drop_column('courses', 'source_version')
    op.drop_column('courses', 'nqr_code')
    op.drop_column('courses', 'nsqf_level')
    op.drop_column('courses', 'rate_per_hour')
    op.drop_column('courses', 'cost_category')
    op.drop_column('courses', 'qualification')
    op.drop_column('courses', 'source_course_code')
    # ### end Alembic commands ###
