"""add_job_urls_to_postings

Revision ID: add_job_urls_to_postings
Revises: f0a225e93d7b
Create Date: 2026-09-06 12:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_job_urls_to_postings'
down_revision: Union[str, None] = 'f0a225e93d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('job_url', sa.String(length=500), nullable=True))
    op.add_column('job_postings', sa.Column('employer_careers_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_postings', 'employer_careers_url')
    op.drop_column('job_postings', 'job_url')
    # ### end Alembic commands ###
