"""phase2a_core_tables

Revision ID: af28c83b5457
Revises: 
Create Date: 2026-08-26 23:34:22.667600

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af28c83b5457'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('ix_job_roles_is_active', 'job_roles', ['is_active'], unique=False)
    op.create_table('skill_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skill_proficiency_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('rank_score')
    )
    op.create_table('states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_districts_state_id', 'districts', ['state_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('skill_type', sa.String(length=20), nullable=False),
    sa.Column('is_emerging', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_skills_category_id', 'skills', ['category_id'], unique=False)
    op.create_index('ix_skills_is_active', 'skills', ['is_active'], unique=False)
    op.create_index('ix_skills_is_emerging', 'skills', ['is_emerging'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_candidate_profiles_district_id', 'candidate_profiles', ['district_id'], unique=False)
    op.create_index('ix_candidate_profiles_user_id', 'candidate_profiles', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('training_level', sa.String(length=50), nullable=True),
    sa.Column('delivery_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("delivery_mode IS NULL OR delivery_mode IN ('in_person', 'online', 'hybrid')", name='ck_courses_delivery_mode'),
    sa.CheckConstraint("status IN ('active', 'draft', 'archived')", name='ck_courses_status'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_district_id', 'courses', ['district_id'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_table('job_role_skills',
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('years_experience_required', sa.Integer(), nullable=True),
    sa.CheckConstraint("importance IN ('mandatory', 'preferred', 'nice_to_have')", name='ck_job_role_skills_importance'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_role_id', 'skill_id')
    )
    op.create_index('ix_job_role_skills_proficiency_level_id', 'job_role_skills', ['proficiency_level_id'], unique=False)
    op.create_index('ix_job_role_skills_skill_id', 'job_role_skills', ['skill_id'], unique=False)
    op.create_table('skill_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('ix_skill_aliases_skill_id', 'skill_aliases', ['skill_id'], unique=False)
    op.create_table('candidate_career_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('target_job_role_id', sa.UUID(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_career_interests_candidate_id', 'candidate_career_interests', ['candidate_id'], unique=False)
    op.create_index('ix_candidate_career_interests_job_role_id', 'candidate_career_interests', ['target_job_role_id'], unique=False)
    op.create_table('candidate_education_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('stream_specialization', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('board_university', sa.String(length=255), nullable=True),
    sa.Column('passing_year', sa.Integer(), nullable=True),
    sa.Column('marks_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_education_history_candidate_id', 'candidate_education_history', ['candidate_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('grade_outcome', sa.String(length=50), nullable=True),
    sa.CheckConstraint("status IN ('enrolled', 'completed', 'dropped')", name='ck_course_enrollments_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'course_id', name='uq_enrollment_candidate_course')
    )
    op.create_index('ix_course_enrollments_candidate_id', 'course_enrollments', ['candidate_id'], unique=False)
    op.create_index('ix_course_enrollments_course_id', 'course_enrollments', ['course_id'], unique=False)
    op.create_index('ix_course_enrollments_status', 'course_enrollments', ['status'], unique=False)
    op.create_table('course_skills',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'skill_id')
    )
    op.create_index('ix_course_skills_skill_id', 'course_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_skills_skill_id', table_name='course_skills')
    op.drop_table('course_skills')
    op.drop_index('ix_course_enrollments_status', table_name='course_enrollments')
    op.drop_index('ix_course_enrollments_course_id', table_name='course_enrollments')
    op.drop_index('ix_course_enrollments_candidate_id', table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index('ix_candidate_education_history_candidate_id', table_name='candidate_education_history')
    op.drop_table('candidate_education_history')
    op.drop_index('ix_candidate_career_interests_job_role_id', table_name='candidate_career_interests')
    op.drop_index('ix_candidate_career_interests_candidate_id', table_name='candidate_career_interests')
    op.drop_table('candidate_career_interests')
    op.drop_index('ix_skill_aliases_skill_id', table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index('ix_job_role_skills_skill_id', table_name='job_role_skills')
    op.drop_index('ix_job_role_skills_proficiency_level_id', table_name='job_role_skills')
    op.drop_table('job_role_skills')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_district_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_candidate_profiles_user_id', table_name='candidate_profiles')
    op.drop_index('ix_candidate_profiles_district_id', table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index('ix_skills_is_emerging', table_name='skills')
    op.drop_index('ix_skills_is_active', table_name='skills')
    op.drop_index('ix_skills_category_id', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_districts_state_id', table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('skill_proficiency_levels')
    op.drop_table('skill_categories')
    op.drop_index('ix_job_roles_is_active', table_name='job_roles')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
