"""phase6 evidence ingestion and validation

Revision ID: ce2f98973f2a
Revises: 09c9b7802578
Create Date: 2026-08-27 12:13:38.780556

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2f98973f2a'
down_revision: Union[str, None] = '09c9b7802578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_accepted', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_deduplicated', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('started', 'completed', 'failed')", name='ck_ingestion_runs_status'),
    sa.CheckConstraint('records_received >= 0 AND records_accepted >= 0 AND records_rejected >= 0 AND records_deduplicated >= 0', name='ck_ingestion_runs_counts'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_id', 'data_ingestion_runs', ['source_id'], unique=False)
    op.create_index('ix_ingestion_runs_started_at', 'data_ingestion_runs', ['started_at'], unique=False)
    op.create_table('job_role_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('ix_job_role_aliases_role_id', 'job_role_aliases', ['job_role_id'], unique=False)
    op.create_table('ingestion_rejected_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('record_key', sa.String(length=255), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('reason_detail', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['data_ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejected_records_run_id', 'ingestion_rejected_records', ['ingestion_run_id'], unique=False)
    op.create_table('industry_consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('consultation_date', sa.Date(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consultations_district_id', 'industry_consultations', ['district_id'], unique=False)
    op.create_index('ix_consultations_employer_id', 'industry_consultations', ['employer_id'], unique=False)
    op.create_table('raw_job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalization_status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('canonical_job_posting_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("normalization_status IN ('pending', 'accepted', 'rejected', 'duplicate', 'unmapped')", name='ck_raw_job_normalization_status'),
    sa.ForeignKeyConstraint(['canonical_job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['data_ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_raw_job_source_external')
    )
    op.create_index('ix_raw_job_ingestion_run_id', 'raw_job_postings', ['ingestion_run_id'], unique=False)
    op.create_index('ix_raw_job_normalization_status', 'raw_job_postings', ['normalization_status'], unique=False)
    op.create_table('employer_curriculum_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('relevant', 'partially_relevant', 'outdated', 'missing_skills', 'proficiency_mismatch', 'equipment_mismatch')", name='ck_curriculum_validation_status'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_curriculum_validations_course_id', 'employer_curriculum_validations', ['course_id'], unique=False)
    op.create_index('ix_curriculum_validations_employer_id', 'employer_curriculum_validations', ['employer_id'], unique=False)
    op.add_column('data_sources', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('data_sources', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('data_sources', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'status')
    op.drop_column('data_sources', 'organization')
    op.drop_column('data_sources', 'source_url')
    op.drop_index('ix_curriculum_validations_employer_id', table_name='employer_curriculum_validations')
    op.drop_index('ix_curriculum_validations_course_id', table_name='employer_curriculum_validations')
    op.drop_table('employer_curriculum_validations')
    op.drop_index('ix_raw_job_normalization_status', table_name='raw_job_postings')
    op.drop_index('ix_raw_job_ingestion_run_id', table_name='raw_job_postings')
    op.drop_table('raw_job_postings')
    op.drop_index('ix_consultations_employer_id', table_name='industry_consultations')
    op.drop_index('ix_consultations_district_id', table_name='industry_consultations')
    op.drop_table('industry_consultations')
    op.drop_index('ix_rejected_records_run_id', table_name='ingestion_rejected_records')
    op.drop_table('ingestion_rejected_records')
    op.drop_index('ix_job_role_aliases_role_id', table_name='job_role_aliases')
    op.drop_table('job_role_aliases')
    op.drop_index('ix_ingestion_runs_started_at', table_name='data_ingestion_runs')
    op.drop_index('ix_ingestion_runs_source_id', table_name='data_ingestion_runs')
    op.drop_table('data_ingestion_runs')
    # ### end Alembic commands ###
