"""add_future_demand_forecasts_table

Revision ID: f0a225e93d7b
Revises: e8122a968356
Create Date: 2026-09-02 09:55:04.990102

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a225e93d7b'
down_revision: Union[str, None] = 'e8122a968356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_demand_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('industry_sector_id', sa.UUID(), nullable=True),
    sa.Column('forecast_horizon', sa.String(length=50), nullable=False),
    sa.Column('current_demand', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('forecast_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_sector_id'], ['industry_sectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_future_demand_forecasts_district_id', 'future_demand_forecasts', ['district_id'], unique=False)
    op.create_index('ix_future_demand_forecasts_forecast_level', 'future_demand_forecasts', ['forecast_level'], unique=False)
    op.create_index('ix_future_demand_forecasts_sector_id', 'future_demand_forecasts', ['industry_sector_id'], unique=False)
    op.create_index('ix_future_demand_forecasts_skill_id', 'future_demand_forecasts', ['skill_id'], unique=False)
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('course_health_scores', 'review_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('curriculum_proposals', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('curriculum_proposals', 'employer_validated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('emerging_technologies', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('government_officials', 'verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.add_column('promotion_audit_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('promotion_audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('technology_skills', 'relevance',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('training_providers', 'verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_providers', 'verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'unverified'::character varying"),
               existing_nullable=False)
    op.alter_column('technology_skills', 'relevance',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'core'::character varying"),
               existing_nullable=False)
    op.drop_column('promotion_audit_logs', 'updated_at')
    op.drop_column('promotion_audit_logs', 'created_at')
    op.alter_column('government_officials', 'verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending_verification'::character varying"),
               existing_nullable=False)
    op.alter_column('emerging_technologies', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.alter_column('curriculum_proposals', 'employer_validated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('curriculum_proposals', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'proposed'::character varying"),
               existing_nullable=False)
    op.alter_column('course_health_scores', 'review_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending_review'::character varying"),
               existing_nullable=False)
    op.drop_column('audit_logs', 'updated_at')
    op.drop_index('ix_future_demand_forecasts_skill_id', table_name='future_demand_forecasts')
    op.drop_index('ix_future_demand_forecasts_sector_id', table_name='future_demand_forecasts')
    op.drop_index('ix_future_demand_forecasts_forecast_level', table_name='future_demand_forecasts')
    op.drop_index('ix_future_demand_forecasts_district_id', table_name='future_demand_forecasts')
    op.drop_table('future_demand_forecasts')
    # ### end Alembic commands ###
