"""phase2c_add_employer_fk

Revision ID: c5a538c2c5a6
Revises: 02d6674f9534
Create Date: 2026-08-27 01:13:06.830771

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a538c2c5a6'
down_revision: Union[str, None] = '02d6674f9534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('industry_sector_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'employers', 'industry_sectors', ['industry_sector_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.drop_column('employers', 'industry_sector_id')
    # ### end Alembic commands ###
