"""phase2b_market_tables

Revision ID: d961fb42716a
Revises: af28c83b5457
Create Date: 2026-08-27 00:20:52.746710

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd961fb42716a'
down_revision: Union[str, None] = 'af28c83b5457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('size_category', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_employers_district_id', 'employers', ['district_id'], unique=False)
    op.create_index('ix_employers_user_id', 'employers', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('experience_min', sa.String(length=20), nullable=True),
    sa.Column('experience_max', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_postings_district_id', 'job_postings', ['district_id'], unique=False)
    op.create_index('ix_job_postings_employer_id', 'job_postings', ['employer_id'], unique=False)
    op.create_index('ix_job_postings_job_role_id', 'job_postings', ['job_role_id'], unique=False)
    op.create_index('ix_job_postings_status', 'job_postings', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('applied', 'screening', 'interviewing', 'offered', 'rejected')", name='ck_applications_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_candidate_id', 'applications', ['candidate_id'], unique=False)
    op.create_index('ix_applications_job_posting_id', 'applications', ['job_posting_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('job_posting_skills',
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.CheckConstraint("importance IN ('mandatory', 'preferred', 'nice_to_have')", name='ck_job_posting_skills_importance'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proficiency_level_id'], ['skill_proficiency_levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_posting_id', 'skill_id')
    )
    op.create_index('ix_job_posting_skills_skill_id', 'job_posting_skills', ['skill_id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('employer_id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('job_posting_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('placement_date', sa.Date(), nullable=True),
    sa.Column('outcome_status', sa.String(length=50), nullable=False),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome_status IN ('placed_full_time', 'placed_part_time', 'self_employed', 'apprenticeship')", name='ck_placements_outcome_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['course_enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('enrollment_id')
    )
    op.create_index('ix_placements_candidate_id', 'placements', ['candidate_id'], unique=False)
    op.create_index('ix_placements_district_id', 'placements', ['district_id'], unique=False)
    op.create_index('ix_placements_employer_id', 'placements', ['employer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_placements_employer_id', table_name='placements')
    op.drop_index('ix_placements_district_id', table_name='placements')
    op.drop_index('ix_placements_candidate_id', table_name='placements')
    op.drop_table('placements')
    op.drop_index('ix_job_posting_skills_skill_id', table_name='job_posting_skills')
    op.drop_table('job_posting_skills')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_job_posting_id', table_name='applications')
    op.drop_index('ix_applications_candidate_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_job_postings_status', table_name='job_postings')
    op.drop_index('ix_job_postings_job_role_id', table_name='job_postings')
    op.drop_index('ix_job_postings_employer_id', table_name='job_postings')
    op.drop_index('ix_job_postings_district_id', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index('ix_employers_user_id', table_name='employers')
    op.drop_index('ix_employers_district_id', table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
